name: Sonar + Auto Docker

on:
  push:
    branches:
      - main

jobs:
  scan-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=plutoaintaplanet
            -Dsonar.projectKey=Plutoaintaplanet_hocr
            -Dsonar.sources=src
            -Dsonar.python.version=3.11

      - name: Quality Gate Check
        uses: SonarSource/sonarqube-quality-gate-action@v1.2.0
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Create Dockerfile if missing
        run: |
          if [ ! -f Dockerfile ]; then
            cat <<EOF > Dockerfile
            FROM python:3.11-slim

            WORKDIR /app

            COPY requirements.txt .
            RUN pip install --no-cache-dir -r requirements.txt

            COPY src ./src

            CMD ["python", "src/main.py"]
            EOF
          fi

      - name: Build Docker Image
        run: docker build -t horc:${{ github.sha }} .